language: node_js
node_js:
  - 12
env:
  - NODE_ENV=production
deploy:
  provider: releases
  api_key: 
    secure: "$GITHUB_OAUTH_TOKEN"
  file: "dist/index.html"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true