name: continuous integration

on:
  push:
    branches: 
      - master 
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    
    timeout-minutes: 30

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with: 
          node-version: "15.x"

      - run: npm ci
      - run: npm run build
